# Netlify configuration file
[build]
  # Directory that contains the deploy-ready HTML files and assets
  publish = "_site/"
  
  # Simplified build command
  command = "bundle install && bundle exec jekyll build"

  [build.environment]
    RUBY_VERSION = "2.7.8"
    BUNDLER_VERSION = "2.4.22"
    NODE_VERSION = "16"
    JEKYLL_ENV = "production"

# Production context settings
[context.production]
  command = "bundle install && bundle exec jekyll build"

# Deploy preview settings  
[context.deploy-preview]
  command = "bundle install && bundle exec jekyll build --drafts"

# Branch deploy settings
[context.branch-deploy]  
  command = "bundle install && bundle exec jekyll build --drafts"

# Basic redirects for SPA-like behavior (optional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
