# Netlify configuration file
[build]
  # Directory that contains the deploy-ready HTML files and assets
  publish = "_site/"
  
  # Build command with RubyGems update
  command = "gem update --system && bundle install && bundle exec jekyll build"

  [build.environment]
    RUBY_VERSION = "3.0.6"
    BUNDLER_VERSION = "2.4.22"
    NODE_VERSION = "18"
    JEKYLL_ENV = "production"

# Production context settings
[context.production]
  command = "gem install bundler:2.4.22 && bundle install && bundle exec jekyll build"

# Deploy preview settings  
[context.deploy-preview]
  command = "gem install bundler:2.4.22 && bundle install && bundle exec jekyll build --drafts"

# Branch deploy settings
[context.branch-deploy]  
  command = "gem install bundler:2.4.22 && bundle install && bundle exec jekyll build --drafts"

# Basic redirects for SPA-like behavior (optional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
